import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import Provider from "./_trpc/Provider";
import { trpcServer } from "@/server/trpc";
import { redirect } from "next/navigation";
import { headers } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>{children}</Provider>
        <Toaster richColors></Toaster>
      </body>
    </html>
  );
}
