import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import SidePanel from "@/components/sidepanel";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Dashboard({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col h-screen gap-6 pb-10">
      <Navbar></Navbar>

      <div className=" lg:flex-1 flex h-[calc(100%-146px)] mx-[5%] relative">
        <SidePanel></SidePanel>
        <div className="lg:ml-[324px] lg:flex-1 h-full overflow-y-auto">
          {children}
        </div>
      </div>
    </div>
  );
}
